In [1]:
import torch
import numpy as np





In [2]:
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
print("using" , device, "device")


using cuda device


In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [8]:
# revision numpy
a = np.array([1,2,3,4])
#
print(a," ",a.dtype)
# fill with zero row and col should be one arg 
b = np.zeros((2,3))
print(b)

[1 2 3 4]   int64
[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
c = np.arange(10,40,5)
print(c)

[10 15 20 25 30 35]


In [ ]:
A = np.array([1,1],[0,1])
B = np.array([2,0],[3,4])
